Repository visualize-admin/electricity-prices-switzerland, pull requests merged in 2025-05, with the labels that each got.

#153 refactor: cleaned up minor visual bugs from ci/cd migration
  src/components/app-layout.tsx
  src/components/charts-generic/interaction/tooltip-box.tsx
  src/components/combobox.tsx
  src/components/detail-page/banner.tsx
  src/components/detail-page/cantons-comparison-range.tsx
  src/components/detail-page/card.tsx
  src/components/detail-page/download-image.tsx
  src/components/detail-page/filter-set-description.tsx
  src/components/detail-page/layout.tsx
  src/components/detail-page/price-components-bars.tsx
  src/components/detail-page/price-distribution-histogram.tsx
  src/components/detail-page/price-evolution-line-chart.tsx
  src/components/detail-page/sidebar.tsx
  src/components/info-dialog.tsx
  src/components/list.tsx
  src/components/map.tsx
  src/components/price-color-legend.tsx
  src/components/radio-tabs.tsx
  src/lib/use-query-state.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/canton/[id].tsx
  src/pages/details/[entity]/[id]/index.tsx
  src/pages/embed.tsx
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/pages/municipality/[id].tsx
  src/pages/operator/[id].tsx
Labels: enhancement, development, refactoring

#154 refactor: updated storybook to use correct application components
  .storybook/preview.css
  .storybook/preview.tsx
  src/components/MUI.stories.tsx
  src/components/charts-generic/histogram/histogram-state.tsx
  src/components/charts-generic/rangeplot/rangeplot-state.tsx
  src/components/combobox.tsx
  src/components/detail-page/cantons-comparison-range.tsx
  src/components/detail-page/download-image.tsx
  src/components/detail-page/price-components-bars.tsx
  src/components/detail-page/price-distribution-histogram.tsx
  src/components/form.tsx
  src/components/header.tsx
  src/components/info-dialog.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/list.tsx
  src/components/logo.tsx
  src/components/price-color-legend.tsx
  src/components/radio-tabs.tsx
  src/components/storybook/base-style.tsx
  src/components/storybook/story-grid.tsx
  src/domain/data.ts
  src/icons/index.tsx
  src/themes/components.tsx
  src/themes/index.d.ts
  src/themes/palette.ts
Labels: documentation, enhancement, development

#158 fix: new ci/cd colors after clients feedback
  src/themes/palette.ts
Labels: development, refactoring

#159 fix: fixed color palette primary detection
  public/assets/checkmark.svg
  public/assets/map-preview.svg
  src/components/button-group.tsx
  src/components/charts-generic/interaction/ruler.tsx
  src/components/charts-generic/lines/lines.tsx
  src/components/combobox.tsx
  src/components/detail-page/cantons-comparison-range.tsx
  src/components/detail-page/price-components-bars.tsx
  src/components/detail-page/price-distribution-histogram.tsx
  src/components/detail-page/sidebar.tsx
  src/components/hint.tsx
  src/components/info-banner.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/list.tsx
  src/components/storybook/base-style.tsx
  src/domain/helpers.tsx
  src/pages/map/index.tsx
  src/themes/components.tsx
  src/themes/palette.ts
Labels: documentation, enhancement, development

#163 chore: download cookie and csv-parser
  .gitignore
  knip.config.ts
  package.json
  src/graphql/queries.graphql
  src/graphql/queries.ts
  src/graphql/resolver-types.ts
  src/graphql/resolvers.ts
  src/graphql/schema.graphql
  src/lib/decrypt-sunshine-csv.ts
  src/lib/encrypt-sunshine-csv.ts
  src/middleware.ts
  src/pages/canton/[id].tsx
  src/pages/embed.tsx
  src/pages/index.tsx
  src/pages/municipality/[id].tsx
  src/pages/operator/[id].tsx
  src/sunshine-data.enc
  yarn.lock
Labels: enhancement, development

#172 Last fixes before final merge
  src/components/app-layout.tsx
  src/components/list.tsx
  src/components/operator-documents.tsx
  src/components/search.tsx
  src/locales/de/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/themes/components.tsx
Labels: enhancement, development, refactoring

#176 chore: Add testing feedback template
  .github/ISSUE_TEMPLATE/testing_feedback.md
Labels: documentation

#175 Improved Mobile View
  src/components/app-layout.tsx
  src/components/button-group.tsx
  src/components/charts-generic/annotation/annotation-x.tsx
  src/components/charts-generic/axis/axis-height-linear.tsx
  src/components/charts-generic/bars/bars-grouped.tsx
  src/components/charts-generic/histogram/histogram-state.tsx
  src/components/charts-generic/interaction/ruler.tsx
  src/components/charts-generic/interaction/tooltip-content.tsx
  src/components/charts-generic/use-chart-theme.ts
  src/components/combobox.tsx
  src/components/detail-page/banner.tsx
  src/components/detail-page/card.tsx
  src/components/detail-page/price-distribution-histogram.tsx
  src/components/detail-page/price-evolution-line-chart.tsx
  src/components/detail-page/selector-multi.tsx
  src/components/electricity-selectors.tsx
  src/components/footer.tsx
  src/components/hint.tsx
  src/components/info-dialog.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/list.tsx
  src/components/map.tsx
  src/components/operator-documents.tsx
  src/components/price-color-legend.tsx
  src/components/search.tsx
  src/components/storybook/base-style.tsx
  src/components/sunshine-charts.stories.tsx
  src/domain/helpers.tsx
  src/lib/use-mobile.ts
  src/locales/de/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/pages/[entity]/[id]/index.tsx
  src/pages/map/index.tsx
  src/themes/components.tsx
Labels: enhancement, development, needs refinement

#155 Feat/homepage sunshine cards
  .storybook/preview.tsx
  CHANGELOG.md
  e2e/storybook.spec.ts
  public/assets/map-sunshine-default.svg
  public/assets/map-sunshine-mountain.svg
  public/assets/map-sunshine-yes-no.svg
  src/pages/index.tsx
Labels: development, needs refinement

#187 Added Details Panel
  CHANGELOG.md
  knip.config.ts
  package.json
  public/assets/map-sunshine-default.svg
  public/assets/map-sunshine-mountain.svg
  public/assets/map-sunshine-yes-no.svg
  src/components/anchor-nav.tsx
  src/components/charts-generic/axis/axis-height-linear.tsx
  src/components/charts-generic/constants.ts
  src/components/charts-generic/lines/lines-state.tsx
  src/components/detail-page/price-evolution-line-chart.stories.tsx
  src/components/detail-page/price-evolution-line-chart.tsx
  src/components/drawer.tsx
  src/components/header.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/list.tsx
  src/components/map-context.tsx
  src/components/map-details-content.tsx
  src/components/map.tsx
  src/components/sunshine/sunshine-card.tsx
  src/components/sunshine/sunshine-topics.tsx
  src/domain/translation.tsx
  src/flags/api.tsx
  src/flags/components.tsx
  src/flags/hooks.ts
  src/flags/index.ts
  src/flags/ls-adapter.ts
  src/flags/store.ts
  src/flags/types.ts
  src/lib/use-event.ts
  src/lib/use-query-state.ts
  src/locales/de/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/pages/[entity]/[id]/index.tsx
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/themes/components.tsx
  src/utils/flags.ts
  yarn.lock
Labels: development, needs refinement, feature
