Repository visualize-admin/electricity-prices-switzerland, pull requests merged in 2025-09, with the labels that each got.

#354 Preserve language when clicking main CTA button
  CHANGELOG.md
  src/pages/index.tsx
Labels: bug

#368 Re-order price components
  src/components/detail-page/cantons-comparison-range.tsx
  src/components/detail-page/price-distribution-histogram.tsx
  src/domain/data.ts
  src/domain/query-states.ts
Labels: bug, enhancement

#390 Adjustments
  CHANGELOG.md
  src/components/combined-selectors/index.tsx
  src/components/electricity-selectors.tsx
  src/components/energy-prices-map.tsx
  src/components/form.tsx
  src/components/info-dialog-props.ts
  src/components/info-dialog.tsx
  src/components/list.tsx
  src/components/map-context.tsx
  src/components/map-layers.tsx
  src/components/map/mobile-controls.tsx
  src/components/network-costs-trend-card.tsx
  src/components/operational-standards-card.tsx
  src/components/overview-card.tsx
  src/components/power-stability-card.tsx
  src/components/sunshine-map.tsx
  src/components/sunshine-selectors/base.tsx
  src/components/tariffs-trend-card.tsx
  src/domain/gitlab-wiki-api.ts
  src/domain/sunshine.ts
  src/domain/wiki.ts
  src/graphql/queries.graphql
  src/graphql/queries.ts
  src/graphql/resolver-types.ts
  src/graphql/resolvers.ts
  src/graphql/schema.graphql
  src/hooks/use-enriched-sunshine-data.ts
  src/lib/db/sparql.ts
  src/locales/aa/messages.po
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/pages/api/graphql.integration.spec.ts
  src/pages/map/index.tsx
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
  src/pages/sunshine/[entity]/[id]/overview.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
  src/themes/components.tsx
  src/utils/platform.ts
Labels: enhancement
