Repository visualize-admin/electricity-prices-switzerland, pull requests merged in 2025-07, with the labels that each got.

#273 Implement Overview Details Page
  CHANGELOG.md
  src/components/detail-page/card.tsx
  src/components/horizontal-bar-chart.stories.tsx
  src/components/map-details-chart-adapters.tsx
  src/components/network-cost-trend-chart.tsx
  src/components/network-costs-trend-card.tsx
  src/components/power-stability-card.tsx
  src/components/power-stability-chart.tsx
  src/components/scatter-plot.stories.tsx
  src/components/sunshine-tabs.tsx
  src/components/table-comparison-card.tsx
  src/components/tariffs-trend-card.tsx
  src/components/tariffs-trend-chart.tsx
  src/domain/query-states.ts
  src/domain/translation.tsx
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
  src/pages/sunshine/[entity]/[id]/operational-standards.tsx
  src/pages/sunshine/[entity]/[id]/overview.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
Labels: development, needs refinement, feature

#277 Homepage sunshine links + Operational standards map
  .github/workflows/e2e.yml
  CHANGELOG.md
  e2e/home.spec.ts
  src/components/list.tsx
  src/components/network-cost-trend-chart.tsx
  src/components/sunshine-map.stories.tsx
  src/components/sunshine-map.tsx
  src/components/sunshine/sunshine-topics.tsx
  src/data/geo.tsx
  src/domain/data.ts
  src/domain/helpers.tsx
  src/domain/query-states.ts
  src/domain/sunshine-accessor.tsx
  src/domain/sunshine-data.ts
  src/domain/translation.tsx
  src/lib/db/sql.ts
  src/lib/db/sunshine-setup.sql
  src/lib/use-query-state.ts
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/pages/map/index.tsx
Labels: enhancement

#282 Add Operational Standards Chart
  CHANGELOG.md
  mocks/sunshine-operationalStandards-compliance-mock.json
  mocks/sunshine-operationalStandards-serviceQuality-mock.json
  src/components/charts-generic/annotation/annotation-x.tsx
  src/components/charts-generic/axis/axis-height-linear.tsx
  src/components/charts-generic/axis/axis-width-histogram.tsx
  src/components/charts-generic/constants.ts
  src/components/charts-generic/histogram/histogram-state.tsx
  src/components/charts-generic/histogram/histogram.stories.tsx
  src/components/charts-generic/histogram/histogram.tsx
  src/components/charts-generic/histogram/median.tsx
  src/components/charts-generic/lines/lines-state.tsx
  src/components/charts-generic/overlay/interaction-histogram.tsx
  src/components/charts-generic/use-chart-state.tsx
  src/components/detail-page/price-evolution-line-chart.tsx
  src/components/network-cost-trend-chart.tsx
  src/components/operational-standards-card.tsx
  src/components/operational-standards-chart.tsx
  src/components/power-stability-chart.tsx
  src/components/tariffs-trend-chart.tsx
  src/domain/config-types.ts
  src/domain/helpers.tsx
  src/domain/metrics.ts
  src/domain/translation.tsx
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/utils/flags.ts
Labels: development, feature

#305 feat: Add additional years with mock data
  .github/pull_request_template.md
  CHANGELOG.md
  src/lib/db/duckdb.ts
  src/lib/db/sunshine-setup.sql
  src/lib/sunshine-csv.ts
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/sunshine-data/Sunshine 2022 28.05.2025.enc
  src/sunshine-data/Sunshine 2023 28.05.2025.enc
  src/sunshine-data/Sunshine 2024 28.05.2025.enc
  src/sunshine-data/Sunshine 2025 28.05.2025.enc
  src/sunshine-data/peer-groups.enc
Labels: data
