Repository visualize-admin/electricity-prices-switzerland, pull requests merged in 2025-06, with the labels that each got.

#196 Add costs and tariffs page
  src/components/button-group.stories.tsx
  src/components/card-grid.stories.tsx
  src/components/card-grid.tsx
  src/components/card-source.tsx
  src/components/combobox.stories.tsx
  src/components/comparison-table.stories.tsx
  src/components/comparison-table.tsx
  src/components/detail-page/sidebar.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/net-tariffs-trend-card.tsx
  src/components/network-costs-trend-card.tsx
  src/components/peer-group-card.tsx
  src/components/storybook/story-grid.tsx
  src/components/table-comparison-card.tsx
  src/components/unit-value-with-trend.tsx
  src/data/shared-page-props.tsx
  src/domain/data.ts
  src/domain/translation.tsx
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
Labels: enhancement

#208 Switch from de to en as default
  .gitignore
  CHANGELOG.md
  knip.config.ts
  lingui.config.js
  next.config.js
  next.config.ts
  package.json
  src/components/header.tsx
  src/data/shared-page-props.tsx
  src/graphql/resolvers.ts
  src/lib/use-locale.ts
  src/locales/config.js
  src/locales/create-po-dummies.sh
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/locales/locales.json
  src/locales/locales.ts
  src/locales/trans-dummy.tsx
  src/pages/[entity]/[id]/index.tsx
  src/pages/embed.tsx
  src/pages/index.tsx
  src/pages/map/index.tsx
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
  src/pages/sunshine/[entity]/[id]/operational-standards.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
  src/rdf/search-queries.ts
  tpo.config.json
  tsconfig.json
  yarn.lock
Labels: enhancement, development, needs refinement, refactoring

#223 chore: updated tpo-deepl
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement, development

#230 Feat/network costs chart
  CHANGELOG.md
  e2e/sunshine.spec.ts
  src/components/comparison-table.stories.tsx
  src/components/detail-page/layout.tsx
  src/components/table-comparison-card.tsx
  src/components/trend-icon.tsx
  src/components/unit-value-with-trend.tsx
  src/domain/translation.tsx
  src/graphql/queries.ts
  src/graphql/resolver-types.ts
  src/graphql/schema.graphql
  src/lib/db/sql.ts
  src/lib/db/sunshine-data.ts
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
Labels: enhancement

#233 Sunshine map (SAIDI & SAIFI)
  CHANGELOG.md
  scripts/sunshine-csv.ts
  src/components/combined-selectors/index.tsx
  src/components/map.mock.ts
  src/components/map.stories.tsx
  src/components/operators-map.tsx
  src/components/sunshine-selectors/base.stories.tsx
  src/components/sunshine-selectors/base.tsx
  src/components/sunshine-selectors/index.tsx
  src/domain/data.ts
  src/domain/sunshine-data.ts
  src/domain/translation.tsx
  src/graphql/resolvers.ts
  src/lib/db/sql.ts
  src/lib/sunshine-csv.ts
  src/lib/use-query-state.ts
  src/pages/map/index.tsx
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
Labels: enhancement

#237 chore: updated tpo
  CHANGELOG.md
  package.json
  yarn.lock
Labels: enhancement, development

#235 Added Horizontal Stacked Bar Chart
  CHANGELOG.md
  src/components/charts-generic/axis/axis-height-categories.tsx
  src/components/charts-generic/axis/axis-height-linear.tsx
  src/components/charts-generic/axis/axis-width-linear.tsx
  src/components/charts-generic/bars/bars-grouped-state.tsx
  src/components/charts-generic/bars/bars-stacked-state.tsx
  src/components/charts-generic/bars/bars-stacked.tsx
  src/components/charts-generic/interaction/tooltip.tsx
  src/components/charts-generic/scatter-plot/dots.tsx
  src/components/charts-generic/scatter-plot/median.tsx
  src/components/charts-generic/scatter-plot/scatter-plot-state.tsx
  src/components/charts-generic/use-chart-state.tsx
  src/components/detail-page/price-components-bars.tsx
  src/components/horizontal-bar-chart.stories.tsx
  src/components/power-stability-card.tsx
  src/components/power-stability-chart.tsx
  src/components/scatter-plot.stories.tsx
  src/domain/config-types.ts
  src/domain/helpers.tsx
  src/domain/translation.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
  src/themes/palette.ts
Labels: development, feature

#239 Histogram story
  src/components/charts-generic/histogram/histogram.stories.tsx
  src/components/charts-generic/histogram/mock.ts
Labels: enhancement

#238 Card Improvements
  src/components/detail-page/download-image.tsx
  src/components/net-tariffs-trend-card.tsx
  src/components/network-costs-trend-card.tsx
  src/components/operational-standards-card.tsx
  src/components/operational-standards-chart.tsx
  src/domain/translation.tsx
  src/pages/sunshine/[entity]/[id]/operational-standards.tsx
Labels: enhancement, development

#242 Accent Translations
  src/components/detail-page/banner.tsx
  src/components/detail-page/sidebar.tsx
  src/components/list.tsx
  src/domain/translation.tsx
  src/locales/create-po-dummies.sh
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
Labels: development, needs refinement

#245 Connect MultiCombobox with Sunshine pages
  CHANGELOG.md
  src/components/charts-generic/bars/bars-stacked-state.tsx
  src/components/combobox.stories.tsx
  src/components/combobox.tsx
  src/components/detail-page/selector-multi.tsx
  src/components/kitchen-sink.stories.tsx
  src/components/net-tariffs-trend-card.tsx
  src/components/net-tariffs-trend-chart.tsx
  src/components/network-cost-trend-chart.tsx
  src/components/network-costs-trend-card.tsx
  src/components/power-stability-card.tsx
  src/components/power-stability-chart.tsx
  src/components/query-combobox.tsx
  src/components/scatter-plot.stories.tsx
  src/domain/helper.spec.ts
  src/domain/helpers.tsx
  src/domain/translation.tsx
Labels: enhancement, development, feature

#246 Feat: Added rendering logic and cleaned up a bit
  src/components/horizontal-bar-chart.stories.tsx
  src/components/net-tariffs-trend-card.tsx
  src/components/net-tariffs-trend-chart.tsx
  src/components/network-cost-trend-chart.tsx
  src/components/network-costs-trend-card.tsx
  src/components/power-stability-card.tsx
  src/components/power-stability-chart.tsx
  src/components/scatter-plot.stories.tsx
  src/pages/sunshine/[entity]/[id]/costs-and-tariffs.tsx
  src/pages/sunshine/[entity]/[id]/power-stability.tsx
Labels: enhancement, development

#255 Release v2.2.0
  CHANGELOG.md
  package.json
Labels: development

#254 Dynamic Tariffs
  CHANGELOG.md
  src/components/charts-generic/bars/bars-grouped-state.tsx
  src/components/charts-generic/bars/bars-grouped.tsx
  src/components/charts-generic/constants.ts
  src/components/detail-page/price-components-bars.tsx
  src/components/hint.tsx
  src/components/info-banner.tsx
  src/locales/de/messages.po
  src/locales/en/messages.po
  src/locales/fr/messages.po
  src/locales/it/messages.po
  src/utils/flags.ts
Labels: development, feature
